language: go

os:
  - linux
  - osx
  - windows

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x

before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go";
    export PATH="$GOPATH/bin:$PATH"; fi
  - mkdir -p ~/bin/ && export PATH="~/bin/:$PATH"

install:
  - go get -u golang.org/x/lint/golint
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
  - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

script:
  - go get -v ./...
  - |-
    case $TRAVIS_OS_NAME in
      linux|osx)
        golint ./... | reviewdog -f=golint -reporter=github-check
        golangci-lint run --out-format=line-number -E goimports -E misspell | reviewdog -f=golangci-lint -reporter=github-check
        golint ./... | reviewdog -f=golint -reporter=github-pr-review
        golangci-lint run --out-format=line-number -E goimports -E misspell | reviewdog -f=golangci-lint -reporter=github-pr-review
        ;;
    esac
  - go test -v -benchmem -test.bench=".*" -coverprofile=coverage.txt -covermode=atomic  ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - GO111MODULE=on
    - secure: H8jY/CdqxA6iBb4XQwL9hYBLskQvm9xuq4UFWMJVzn6HiKXF33gsiGyx2ExvJPz+Pjmm3hzd6OxD+0mLHiQfET/BpYpbvYW3zrBLtZosAKDKpoZkBxVP1zz70l4bG+wFMCNf07Q65uWw76LPdwfTWivvFlRWP8IjbdyIQo6Ph0HZ06wFCdXdBYXUcXO7eJ0dH2yM8pln1IngUBQTHufNm8nWJCdULvWX0QLqXavY7D99wnZ3MGTyJF0JAARYwCN/hCwHxbO1FIqPeaf0vugRv/qPeRiHpcCHeVuq7KgMwm7kJoH/DTxxyxmyxEBiHeOcznnL2jREfxNXzpRsdXZf2j5arrwW46ZP6FKXen9KUzUxtc0PFVZ9tjNx6LtzRzhf6xEqm7w2eQUqCsfl9VN3DymH6to5Z6cVRJjnrS5CcPnIjCKc1IsrauQ11OkzA9DHqahHzGHMziAZXe2GlozKK/DO1HXKQ3J8fA6SW4zIsTcROtwTwK+Kvpnhf5flqmhrjDUuI2XQ1RF5zt2cQ29a/w8QIohM0sY7vdZwUy3cWs4nk5SJMiptf/++UUxYCbgJ2MssmivLv8PL7MGPrIlLZgh5QsgRuBctpILQ1bgTnrTuayDINZm8toQEJ5Dbxadh5xAqKKmuKL14cExw1j9qO1RHp/4roORV3nclp/lm/XM=